import React, { FormEvent, useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Boxes, Building2, LayoutDashboard, LogOut, PackageSearch, ShieldCheck, Users } from 'lucide-react';
import './styles.css';
const API = import.meta.env.VITE_API_URL ?? 'http://localhost:3000/api';
type Product = { id:string; internalCode:string; name:string; generalPrice:string; category:{name:string}; branches:unknown[] };
async function request<T>(path:string, token?:string, options?:RequestInit):Promise<T>{ const response=await fetch(`${API}${path}`,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}); if(!response.ok) throw new Error((await response.json()).message ?? 'Error inesperado'); return response.json(); }
function App(){
 const [token,setToken]=useState(localStorage.getItem('accessToken')??''); const [error,setError]=useState(''); const [products,setProducts]=useState<Product[]>([]);
 useEffect(()=>{if(token) request<Product[]>('/products',token).then(setProducts).catch(()=>{localStorage.clear();setToken('')})},[token]);
 async function login(e:FormEvent<HTMLFormElement>){e.preventDefault();setError('');const data=new FormData(e.currentTarget);try{const result=await request<{accessToken:string}>('/auth/login',undefined,{method:'POST',body:JSON.stringify({identifier:data.get('identifier'),password:data.get('password')})});localStorage.setItem('accessToken',result.accessToken);setToken(result.accessToken)}catch(err){setError((err as Error).message)}}
 if(!token)return <main className="login"><section className="login-card"><div className="brand-mark"><Boxes/></div><p className="eyebrow">ADMINISTRACIÓN CENTRAL</p><h1>El Rincón de<br/>los Nietos</h1><p className="muted">Ingresá para administrar tus sucursales.</p><form onSubmit={login}><label>Usuario o email<input name="identifier" autoFocus required defaultValue="admin"/></label><label>Contraseña<input name="password" type="password" required/></label>{error&&<p className="error">{error}</p>}<button>Ingresar al sistema</button></form><small>Acceso protegido y auditable</small></section></main>;
 return <div className="shell"><aside><div className="side-brand"><Boxes/><span>El Rincón<small>de los Nietos</small></span></div><nav><a className="active"><LayoutDashboard/>Inicio</a><a><PackageSearch/>Productos</a><a><Building2/>Sucursales</a><a><Users/>Usuarios</a><a><ShieldCheck/>Roles y permisos</a></nav><button className="logout" onClick={()=>{localStorage.clear();setToken('')}}><LogOut/>Cerrar sesión</button></aside><main className="content"><header><div><p className="eyebrow">RESUMEN GENERAL</p><h2>Buen día 👋</h2><p className="muted">Núcleo operativo de tu cadena de almacenes.</p></div><span className="status">● SISTEMA ONLINE</span></header><section className="cards"><article><span>Sucursales activas</span><strong>3</strong><small>Centro, Plaza y Norte</small></article><article><span>Productos cargados</span><strong>{products.length}</strong><small>Catálogo centralizado</small></article><article><span>Moneda principal</span><strong>ARS</strong><small>Pesos argentinos</small></article></section><section className="panel"><div className="panel-title"><div><h3>Catálogo de productos</h3><p className="muted">Precio general y disponibilidad multi-sucursal.</p></div><button>+ Nuevo producto</button></div><table><thead><tr><th>Producto</th><th>Código</th><th>Categoría</th><th>Precio general</th><th>Estado</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td><b>{p.name}</b></td><td>{p.internalCode}</td><td>{p.category.name}</td><td>{new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS'}).format(Number(p.generalPrice))}</td><td><span className="badge">Activo</span></td></tr>)}</tbody></table></section></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
