ALTER TABLE "Role" ADD COLUMN "systemRole" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Permission" ADD COLUMN "module" TEXT NOT NULL DEFAULT 'GENERAL', ADD COLUMN "label" TEXT NOT NULL DEFAULT '', ADD COLUMN "sortOrder" INTEGER NOT NULL DEFAULT 0;
UPDATE "Role" SET "systemRole" = true WHERE "code" IN ('SUPER_ADMIN','ADMIN','ENCARGADO','CAJERO','REPOSITOR');
